### ISSUE TITLE
Game crash when spawning an AI that has a controller with AdvancedSight Component enabled (after latest update)

### ISSUE THREAD

**Issue by Tom90210x** [rlewicki/AdvancedSightSupport#14]
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000448

UnrealEditor_AdvancedSight!UE::CoreUObject::Private::ResolveObjectHandleNoRead() [D:\RocketSync\5.2.0-25360045+++UE5+Release-5.2\Working\Engine\Source\Runtime\CoreUObject\Public\UObject\ObjectHandle.h:255]
UnrealEditor_AdvancedSight!UAdvancedSightComponent::BeginPlay() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AdvancedSight\Source\AdvancedSight\Private\AdvancedSightComponent.cpp:276]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by rlewicki** [comment]
Hi @Tom90210x! Thanks for reaching out. The call stack you posted indicates that the owner of that component is not a `AController` based class. If this is true, you should be able to open a log file and see following error message:
```
"AdvancedSightComponent attached to %s. This component should be attached to a AController based class."
```
where `%s` is the name of the actor.

Could you please confirm that this is not the case?

I'd also like to mention that there is a community discord server if you prefer communicating via Discord rather than GitHub issues: https://discord.gg/ggESDp6MBP

**Comment by Tom90210x** [comment]
Hi,
thanks for the quick response.
Yes you are right, the crash-log has this message:
"AdvancedSightComponent attached to %s. This component should be attached to a AController based class."

But my character is actually based on an AController
And everything was working fine in a UE5 third-person template project.
Got a message that there is an update 1.3 and after the update the editor crashes when trying to play.

P.S. Ok I'll create a topic in discord.
